# Generated by Django 4.2 on 2023-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_confirmemailmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmemailmodel",
            name="code",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
